name: pokedex
description: App that catalogues information regarding the various species of PokÃ©mon
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  responsive_builder: ^0.3.0
  cupertino_icons: ^1.0.0
  dio: ^3.0.10
  flutter_svg: ^0.18.1
  transparent_image: ^1.0.0
  get_it: ^5.0.1
  either_option: ^1.0.0
  provider: ^4.3.2+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_model:
  build_runner: ^1.0.0
  json_serializable: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/svgs/
    - assets/images/
  fonts:
   - family: WorkSans
     fonts:
       - asset: fonts/WorkSans-Medium.ttf
   - family: Moret
     fonts:
       - asset: fonts/Moret-Regular.ttf

